-- V1: initial schema for the URL mapping table (create-short-URL vertical slice).
-- PostgreSQL-specific. Column sizes/nullability are chosen to match the UrlMapping entity
-- mapping exactly, since Hibernate runs with ddl-auto=validate against this schema.

CREATE TABLE url_mapping (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url VARCHAR(2048)            NOT NULL,
    short_code   VARCHAR(7)               NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    click_count  BIGINT                   NOT NULL DEFAULT 0,

    CONSTRAINT uq_url_mapping_short_code UNIQUE (short_code),
    CONSTRAINT chk_url_mapping_short_code_length CHECK (char_length(short_code) = 7)
);

-- No separate CREATE INDEX on short_code: the UNIQUE constraint above already creates one,
-- and it's the lookup path the (not-yet-built) redirect endpoint will use.
